### ISSUE TITLE
Gießdienst eintragen nach UX Design im Frontend umsetzten 

### ISSUE THREAD

**Issue by bastiion** [community-garden/pergola-fullstack#10]
Das Eintragen von Gießdienste als Statemachine auf der Basis der erarbeiteten UX Vorlagen umsetzten.

eintragen Prozess als ganzes modular aufbauen. Komplexere Unterkomponenten in separatem Issue.

ab Seite 2

Hierfür halte ich die Verwendung von Redux zum internen Statemangement für sinnvoll.

https://xd.adobe.com/view/a5e2f600-6792-466f-bfe3-fb3b988d89de-f0b1

**Comment by pminf** [comment]
@bastiion Die Möhren wachsen nun: https://github.com/community-garden/pergola-frontend/pull/5

**Comment by cariboula** [comment]
Datumsanzeige muss angepasst werden (zumindest wenn der aktuelle Stand noch derLive-Demo entspricht):
![grafik](https://user-images.githubusercontent.com/73436109/104052842-95a8d900-51ea-11eb-9ac1-877917dbf456.png)

Bei Monatswechsel sollte auch das erste Datum über einen Monat verfügen.

**Comment by pminf** [comment]
Wurde im Grunde erledigt. Alles weitere dann in kleineren Tickets.
