### ISSUE TITLE
App Gerüst entschlacken, Welcome Screen und Menu

### ISSUE THREAD

**Issue by bastiion** [community-garden/pergola-fullstack#14]
App für den Einbau der Module vorbereiten. Simpler WelcomeScreen (späteres Dashboard/ What's Up)

Menu Leiste mit Links und Icons zum Gießplan, Terminkalender, zur Karte und zum Planer.

**Comment by cariboula** [comment]
@bastiion Würde das auch als Design Task mitnehmen (und dann gleich mit dem Gießplan Flow in den Nutzertest nehmen)

**Comment by cariboula** [comment]
@bastiion Habe die Screens geupdated, die kannst du gern nutzen: https://xd.adobe.com/view/7aee4b9e-13a4-47c4-8627-6b972f40a5f6-2fbd/ Details gibt's rechts im Dev-Mode </> unter dem Kommentar-Icon, auch wenn ich nicht glaube, dass du das zum aktuellen Zeitpunkt brauchst :)
