### ISSUE TITLE
Let it rain 0.2

### ISSUE THREAD

**Issue by cariboula** [community-garden/pergola-fullstack#18]
Design der nächsten Version des Let it rain Flows (Gießdienste eintragen + Kalenderansicht) 

- Feedback aus dem Team nutzen
- UX Test-Dokumentation nutzen
- Akzeptanzkriterien gegenprüfen

https://xd.adobe.com/view/a5e2f600-6792-466f-bfe3-fb3b988d89de-f0b1/

**Comment by cariboula** [comment]
v0.2 ist fertig: https://xd.adobe.com/view/a5e2f600-6792-466f-bfe3-fb3b988d89de-f0b1/

@pminf oder @bastiion Bitte um Review - einfach Issue zuweisen :-)

TBD: 
- Spontangießen
- Absagen
- Drucken
- Desktop-Ansicht

Wenn euch die Findings aus den UX Tests interessieren und warum ich wo in welcher Reihenfolge was geändert hab, gibt es im [GitGra](https://git.gra.one/prototype2020/module/issues/6#note_645) die Excel dazu.

**Comment by pminf** [comment]
@cariboula 

1. Beim Einsehen der kommenden Gießzeiten hat man die Woche von Montag bis Sonntag im Blick. Das hat zur Folge, dass man am Sonntag nicht sieht, dass man nächsten (Mon-)Tag gießen muss. 
2. Beim Absagen wäre ein Confirm-Dialog sinnvoll, um versehentliche Absagen zu vermeiden.

**Comment by pminf** [comment]
@cariboula 

1. Beim Einsehen der kommenden Gießzeiten hat man die Woche von Montag bis Sonntag im Blick. Das hat zur Folge, dass man am Sonntag nicht sieht, dass man nächsten (Mon-)Tag gießen muss. 
2. Beim Absagen wäre ein Confirm-Dialog sinnvoll, um versehentliche Absagen zu vermeiden.

**Comment by pminf** [comment]
@cariboula Habe noch etwas im Entwurf kommentiert. Ansonsten habe ich nichts hinzufügen. Das Design ist schön, bedienbar und schlüssig. Tolle Arbeit :)
