### ISSUE TITLE
MVP Definition für Gardentime (Workshops und Events)

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/pergola-fullstack#27]

**Comment by gemeinga-manager** [comment]
Minimal lauffähige Version...

Anforderungen und Wünsche an die Funktionen des Kalenders müssen gesammelt und nach Wichtigkeit sortiert werden

**Comment by bastiion** [comment]
- Minimalversion, ganz simpel (einmaliger Termin, Beschreibung, Ort)
- Eintragen und Abruf der Termine über CalDav
   - regelmäßige Termine und einmalige Termine beachten
   - Klassensystem für Termine (rdf:type relation), dadurch verschieden Arten (Workshop, Event, party, Pflanzaktion (beliebig erweiterbar durch Garten Maintainer))
- Kalenderdarstellung in der App,
- Darstellung im 'Was geht' Dashboard

**Comment by gemeinga-manager** [comment]
Termine aus dem Wurzelwerk (regelmäßige Termine + kurzfristige Aktionen)
Möglichkeit Terminen zuzusagen (bei WW-Terminen)
Möglichkeit Termine einzutragen ggf. bestehende editieren
individuelle Benachrichtugungen/ Erinnerungen
Integration in privaten Kalender

**Comment by gemeinga-manager** [comment]
Kalender
Schnittstelle zu Website von UFER (?)

**Comment by gemeinga-manager** [comment]
https://git.gra.one/prototype2020/module/issues/3
