### ISSUE TITLE
Workflow Gardenplaner

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/pergola-fullstack#29]
Ein Workflow erleichtert UX-Entwurf und Programmierung. Beide können parallel laufen, wenn sie auf der gleichen Grundlage entstehen. unsere Gedanken aus dem Starter müssen nun also in Form gebracht werden.

**Comment by gemeinga-manager** [comment]
![workflow_k](https://user-images.githubusercontent.com/72280627/103469291-39196a00-4d63-11eb-893a-008fbd311db0.jpg)

**Comment by gemeinga-manager** [comment]
mir ist noch etwas unklar, durch wen und an welcher Stelle die Termine ihre Kategorie bekommen

**Comment by bastiion** [comment]
Wir könnten die Termine in der App selbst nachträglich zu Kategorien zuweisen mit einem Automatismus abhängig vom Titel (wenn im Titel "Workshop" vorkommt).

**Comment by gemeinga-manager** [comment]
Ja, bei Workshops ist das relativ einfach, weil sie ja aus dem UFER-Kalender kommen, wo ausschließlich (?) workshops notiert sind. Andere Kalender oder Eintrge müssten dann entsprechend mit Stichworten gepflegt werden...

**Comment by cariboula** [comment]
tbd @gemeinga-manager Bitte in Modul-Issue im GitGra Ergebnisse dokumentieren, dann Issue hier auf Done schieben
