### ISSUE TITLE
Let it rain 0.1

### ISSUE THREAD

**Issue by cariboula** [community-garden/pergola-fullstack#3]
**Beschreibung**
Als Entwicklungsteam brauchen wir eine Visualisierung des Gießplanmoduls, um dieses frühzeitig testen zu können.

**Lösung**

- Entwicklung eines Wireframe Konzepts für das Gießplanmodul v1
- umfasst mindestens MUSS-Anforderungen und zusätzlich (ggf. angedeutet) KANN-Anforderungen entsprechend https://git.gra.one/prototype2020/module/issues/6#note_622
- basiert auf diesem Flowchart https://codimd.gra.one/s/ByHxXUZjv#

**Comment by cariboula** [comment]
v0.1 updated link: https://xd.adobe.com/view/7aee4b9e-13a4-47c4-8627-6b972f40a5f6-2fbd/

**Comment by cariboula** [comment]
An @pminf assigned für ein Review (asap) hinsichtlich ... 
- Fehlen wichtige Funktionen, die wir für die v1 vorgesehen haben? (wichtig: hier ist nur die Gärtnersicht dargestellt - Gartenmanager und weitere andere Rollen sind tbd)
- Birgt der Prototyp irgendwelche Sackgassen / unlogische Verknüpfungen usw.?
- Gibt es noch irgendetwas, das sich deiner Meinung nach bis Montag (-> UX Testing) gut integrieren ließe?

**Comment by pminf** [comment]
Das ist wirklich super geworden! 

> Fehlen wichtige Funktionen, die wir für die v1 vorgesehen haben?

- Alles da, bis auf die Druckfunktion. Evtl. hast du das für den Hutmensch vorgesehen, aber an sich sollte es jedem zugänglich sein.

> Birgt der Prototyp irgendwelche Sackgassen / unlogische Verknüpfungen usw.?

Intuitiver Flow 👍 

- Beim nachträglichen Eintragen fehlt die Berücksichtigung der bereits gewählten Tage. Dadurch wirkt es so, dass man seine Verfügbarkeit gänzlich überschreibt. Außerdem finde ich, dass das Ergänzen eines Tages genau so einfach sein sollte wie das Absagen. Gerade sind da aber ein paar Klicks mehr notwendig.
- Da wir dem Nutzer nach dem Eintragen der Verfügbarkeiten nicht unmittelbar sagen können, wann er gießen muss, sollten wir ihn darüber informieren, was nun passiert (weitere Verfügbarkeiten sammeln, Stichtag abwarten, bestmögliche Verteilung berechnen, du wirst informiert!). So können wir ihn mit einem guten Gefühl zurück lassen (es geht alles seinen Gang, darauf kannst du dich verlassen).
- Trägt man zum ersten mal seine Verfügbarkeiten ein, könnte man bei "Wann hast du Zeit?" wohl möglich befürchten, dass man sich hier schon auf Tage festlegt, an denen man gießen wird. Die Bezeichnung "Termine" verstärkt das noch. Wir sollten eingangs ein paar Worte zum Ablauf verlieren oder unter der Überschrift den jeweiligen Schritt kurz erklären.

Nitpicks:
- bei der Auswahl der Tage ist der Monat nicht ersichtlich
- am 24. Juni ist der Tag im Kalender farblich als "wenig Gießer" markiert, wenn man ihn auswählt sind "genug Gießer*innen am Start"

> Gibt es noch irgendetwas, das sich deiner Meinung nach bis Montag (-> UX Testing) gut integrieren ließe?

- Die Druckfunktion lässt sich sicher gut andeuten. 
- Die eben erwähnten textuellen Hinweise könnte man noch ergänzen.
