### ISSUE TITLE
setup social identity providers

### ISSUE THREAD

**Issue by johannesloetzsch** [community-garden/pergola-fullstack#47]
https://www.keycloak.org/docs/latest/server_admin/#social-identity-providers

**Comment by johannesloetzsch** [comment]
- [x] Github, Facebook, …

- [ ] Nextcloud

- [ ] Trello?

**Comment by pminf** [comment]
Danke sehr, funktioniert prinzipiell. Github ist bereits integriert, Trello (#75) und Nextcloud (#76) folgend hoffentlich noch. Etwaige weitere Provider werden in separaten Tickets behandelt.
