### ISSUE TITLE
Beispieldaten von Wurzelwerk

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/pergola-fullstack#54]

**Comment by gemeinga-manager** [comment]
@bastiion Zu welchem Thema wolltest du mit diesem Issue Beispiedaten vom WW haben? Ich suche sie gern raus...

**Comment by bastiion** [comment]
@gemeinga-manager danke, es ging um Beispieldaten vom Gießplan. Hat sich mittlerweile aber erledigt, weil wir auf synthetischen Daten Arbeiten. Ich schließe Mal den issue
