### ISSUE TITLE
Feedback-Button in Demo einbauen

### ISSUE THREAD

**Issue by cariboula** [community-garden/pergola-fullstack#66]
![grafik](https://user-images.githubusercontent.com/73436109/107154989-28699e80-6976-11eb-9fb3-08f5bef96bd6.png)
Material UI FAB in accent color with comment icon 

import ModeCommentIcon from '@material-ui/icons/ModeComment';

link: https://stephho.typeform.com/to/eTiWosV0

**Comment by cariboula** [comment]
@bastiion Bitte auf allen Start-Screens einbinden :-)

**Comment by pminf** [comment]
Demoweek ist vorbei und das Ticket damit obsolet.
