### ISSUE TITLE
Login-Schranke (Modal) einbauen

### ISSUE THREAD

**Issue by cariboula** [community-garden/pergola-fullstack#81]
Nutzer sollten über ein Modal zum Login aufgefordert werden, wenn sie versuchen
- einen neuen Gießplaneintrag zu tätigen (über das + in der Toolbar) und später auch über den Link in der Tages-Detailansicht: https://github.com/community-garden/pergola-fullstack/issues/79
- sobald https://github.com/community-garden/pergola-fullstack/issues/63 done, bei Klick auf das Profil-Icon

Das Modal sollte enthalten:
- Heading: Mooooment...
- Body: Bitte melde dich an, um weiterzumachen.
- ggf. Icon
- Primary Button: Anmelden
- X Icon oben rechts: schließen
- ggf. dezenter Text Button unten: Zurück

https://xd.adobe.com/view/8bedab9e-2ef1-4b5a-bb1d-51ed4202c8ac-debe/screen/52596278-6d09-4a50-98fb-238169114ea1/specs/

**Comment by pminf** [comment]
Ist umgesetzt. Habe den Dialog für den Watering Wizard und die Settings Page (welche ansonsten leer ist) eingebunden.
