### ISSUE TITLE
Externe Interessierte zur Demo-Präsentation einladen

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/pergola-fullstack#82]
Ist das gewollt?
Ist das erlaubt?

Claudia fragt bei PT nach und lädt ggf. Vancouver und Testgemeinde ein.

**Comment by gemeinga-manager** [comment]
@johannesloetzsch @pminf @bastiion @cariboula Nicht möglich, da es keine Präsentation geben wird! Es sei denn, wir organisieren das selbst...

**Comment by pminf** [comment]
Demo ist vorbei und das Ticket damit nicht mehr relevant.
