### ISSUE TITLE
KeyCloak Login Template

### ISSUE THREAD

**Issue by johannesloetzsch** [community-garden/pergola-fullstack#83]
https://www.baeldung.com/keycloak-custom-login-page

**Comment by pminf** [comment]
Ich bin soweit fertig: https://github.com/community-garden/pergola-frontend/pull/6 +  https://github.com/community-garden/pergola-fullstack/pull/84

![grafik](https://user-images.githubusercontent.com/611165/108580415-aee58f00-732b-11eb-92f1-6529ed974fa8.png)


@johannesloetzsch Wir müssen noch dafür sorgen, dass 

1. das neue Theme "Pergola" tatsächlich zur Anwendung kommt
2. Der Anzeigename "Pergola" ist
3. Die Standardsprache "Deutsch" ist

Ersteres könnte man wohl über die .env-Variable setzen. Den Rest auch? Oder eher über die keycloak.config?

**Comment by pminf** [comment]
Die Anpassung ist dank Basti nun im Master.

Ich muss die Übersetzung noch ein wenig anpassen und außerdem dafür sorgen, dass die alternativen Loginmethoden gestaltet sind.

**Comment by pminf** [comment]
Ich habe 
- noch ein paar Darstellungsfehler beseitigt
- die Social Login Provider Auflistung verschönert
- Required Fields kenntlich gemacht
- erlaubt, dass man auch ohne Eingaben von der Registrierung zur Anmeldung zurück kommt
- etwas am Wording geschraubt
